<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" ignored="0" total="13" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite" duration-ms="191077" started-at="2019-09-17T12:29:12 CDT" finished-at="2019-09-17T12:32:23 CDT">
    <groups>
      <group name="functest">
        <method signature="LoginTestNG.login1()[pri:1, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login1" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login10()[pri:10, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login10" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login11()[pri:11, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login11" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login12()[pri:12, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login12" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login13()[pri:13, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login13" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login2()[pri:2, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login2" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login3()[pri:3, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login3" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login4()[pri:4, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login4" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login5()[pri:5, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login5" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login6()[pri:6, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login6" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login7()[pri:7, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login7" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login8()[pri:8, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login8" class="com.hexaware.testscripts.Login.LoginTestNG"/>
        <method signature="LoginTestNG.login9()[pri:9, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login9" class="com.hexaware.testscripts.Login.LoginTestNG"/>
      </group> <!-- functest -->
    </groups>
    <test name="Test" duration-ms="191077" started-at="2019-09-17T12:29:12 CDT" finished-at="2019-09-17T12:32:23 CDT">
      <class name="com.hexaware.testscripts.Login.LoginTestNG">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="11483" started-at="2019-09-17T12:29:12 CDT" finished-at="2019-09-17T12:29:23 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login1()[pri:1, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login1" duration-ms="2337" started-at="2019-09-17T12:29:23 CDT" finished-at="2019-09-17T12:29:26 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login1 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1727" started-at="2019-09-17T12:29:26 CDT" finished-at="2019-09-17T12:29:28 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login1 status=SUCCESS method=LoginTestNG.login1()[pri:1, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="9772" started-at="2019-09-17T12:29:28 CDT" finished-at="2019-09-17T12:29:37 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login2()[pri:2, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login2" duration-ms="2555" started-at="2019-09-17T12:29:37 CDT" finished-at="2019-09-17T12:29:40 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login2 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1568" started-at="2019-09-17T12:29:40 CDT" finished-at="2019-09-17T12:29:41 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login2 status=SUCCESS method=LoginTestNG.login2()[pri:2, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="9259" started-at="2019-09-17T12:29:41 CDT" finished-at="2019-09-17T12:29:51 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login3()[pri:3, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login3" duration-ms="2525" started-at="2019-09-17T12:29:51 CDT" finished-at="2019-09-17T12:29:53 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login3 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1758" started-at="2019-09-17T12:29:53 CDT" finished-at="2019-09-17T12:29:55 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login3 status=SUCCESS method=LoginTestNG.login3()[pri:3, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="9401" started-at="2019-09-17T12:29:55 CDT" finished-at="2019-09-17T12:30:04 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="login4()[pri:4, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login4" duration-ms="2633" started-at="2019-09-17T12:30:04 CDT" finished-at="2019-09-17T12:30:07 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Does not display a message // did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Does not display a message // did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.hexaware.testscripts.Login.LoginTestNG.login4(LoginTestNG.java:248)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login4 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1754" started-at="2019-09-17T12:30:07 CDT" finished-at="2019-09-17T12:30:09 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login4 status=FAILURE method=LoginTestNG.login4()[pri:4, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="9648" started-at="2019-09-17T12:30:09 CDT" finished-at="2019-09-17T12:30:18 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="login5()[pri:5, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login5" duration-ms="2400" started-at="2019-09-17T12:30:18 CDT" finished-at="2019-09-17T12:30:21 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Does not display a message // did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Does not display a message // did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.hexaware.testscripts.Login.LoginTestNG.login5(LoginTestNG.java:295)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login5 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1942" started-at="2019-09-17T12:30:21 CDT" finished-at="2019-09-17T12:30:23 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login5 status=FAILURE method=LoginTestNG.login5()[pri:5, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="8597" started-at="2019-09-17T12:30:23 CDT" finished-at="2019-09-17T12:30:31 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login6()[pri:6, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login6" duration-ms="2328" started-at="2019-09-17T12:30:31 CDT" finished-at="2019-09-17T12:30:34 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login6 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1803" started-at="2019-09-17T12:30:34 CDT" finished-at="2019-09-17T12:30:35 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login6 status=SUCCESS method=LoginTestNG.login6()[pri:6, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="10284" started-at="2019-09-17T12:30:35 CDT" finished-at="2019-09-17T12:30:46 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="login7()[pri:7, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login7" duration-ms="2169" started-at="2019-09-17T12:30:46 CDT" finished-at="2019-09-17T12:30:48 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Does not display a mesaage// did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Does not display a mesaage// did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.hexaware.testscripts.Login.LoginTestNG.login7(LoginTestNG.java:391)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login7 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1885" started-at="2019-09-17T12:30:48 CDT" finished-at="2019-09-17T12:30:50 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login7 status=FAILURE method=LoginTestNG.login7()[pri:7, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="9194" started-at="2019-09-17T12:30:50 CDT" finished-at="2019-09-17T12:30:59 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login8()[pri:8, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login8" duration-ms="2380" started-at="2019-09-17T12:30:59 CDT" finished-at="2019-09-17T12:31:01 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login8 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1727" started-at="2019-09-17T12:31:01 CDT" finished-at="2019-09-17T12:31:03 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login8 status=SUCCESS method=LoginTestNG.login8()[pri:8, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="17893" started-at="2019-09-17T12:31:03 CDT" finished-at="2019-09-17T12:31:21 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login9()[pri:9, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login9" duration-ms="2437" started-at="2019-09-17T12:31:21 CDT" finished-at="2019-09-17T12:31:23 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login9 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1505" started-at="2019-09-17T12:31:23 CDT" finished-at="2019-09-17T12:31:25 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login9 status=SUCCESS method=LoginTestNG.login9()[pri:9, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="9765" started-at="2019-09-17T12:31:25 CDT" finished-at="2019-09-17T12:31:35 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="login10()[pri:10, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login10" duration-ms="1573" started-at="2019-09-17T12:31:35 CDT" finished-at="2019-09-17T12:31:36 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Does not redirect to another page // did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Does not redirect to another page // did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.hexaware.testscripts.Login.LoginTestNG.login10(LoginTestNG.java:540)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login10 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1898" started-at="2019-09-17T12:31:36 CDT" finished-at="2019-09-17T12:31:38 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login10 status=FAILURE method=LoginTestNG.login10()[pri:10, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="9031" started-at="2019-09-17T12:31:38 CDT" finished-at="2019-09-17T12:31:47 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="login11()[pri:11, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login11" duration-ms="1662" started-at="2019-09-17T12:31:47 CDT" finished-at="2019-09-17T12:31:49 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Does not redirect to another page // did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Does not redirect to another page // did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.hexaware.testscripts.Login.LoginTestNG.login11(LoginTestNG.java:573)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login11 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="1836" started-at="2019-09-17T12:31:49 CDT" finished-at="2019-09-17T12:31:51 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login11 status=FAILURE method=LoginTestNG.login11()[pri:11, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="12117" started-at="2019-09-17T12:31:51 CDT" finished-at="2019-09-17T12:32:03 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="login12()[pri:12, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login12" duration-ms="3178" started-at="2019-09-17T12:32:03 CDT" finished-at="2019-09-17T12:32:06 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Does not redirect to another page to log in with google // did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Does not redirect to another page to log in with google // did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.hexaware.testscripts.Login.LoginTestNG.login12(LoginTestNG.java:609)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login12 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="2327" started-at="2019-09-17T12:32:06 CDT" finished-at="2019-09-17T12:32:08 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login12 status=FAILURE method=LoginTestNG.login12()[pri:12, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="setup" is-config="true" duration-ms="9605" started-at="2019-09-17T12:32:08 CDT" finished-at="2019-09-17T12:32:18 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="login13()[pri:13, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="login13" duration-ms="2575" started-at="2019-09-17T12:32:18 CDT" finished-at="2019-09-17T12:32:21 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Does not display the message // did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Does not display the message // did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.hexaware.testscripts.Login.LoginTestNG.login13(LoginTestNG.java:656)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login13 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd]" name="tearDown" is-config="true" duration-ms="2474" started-at="2019-09-17T12:32:21 CDT" finished-at="2019-09-17T12:32:23 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login13 status=FAILURE method=LoginTestNG.login13()[pri:13, instance:com.hexaware.testscripts.Login.LoginTestNG@26aa12dd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hexaware.testscripts.Login.LoginTestNG -->
    </test> <!-- Test -->
  </suite> <!-- TestSuite -->
</testng-results>
